name: Mover Renders Automaticamente

on:
  workflow_dispatch: # Esto permite que lo ejecutes manualmente con un botón

jobs:
  move-files:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Crear carpeta de destino si no existe
        run: mkdir -p jgmfut-assets/faces

      - name: Mover archivos render_id
        run: |
          # Mueve todas las imágenes que empiecen con render_id a la carpeta destino
          mv render_id* jgmfut-assets/faces/ || echo "No se encontraron más archivos"

      - name: Confirmar y guardar cambios en GitHub
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add jgmfut-assets/faces/
          git commit -m "Mover automaticamente archivos render_id a jgmfut-assets/faces" || echo "Sin cambios"
          git push
